export const POST_LOAD_START = "POST_LOAD_START";
export const POST_LOAD_SUCCESS = "POST_LOAD_SUCCESS";
export const POST_LOAD_FAIL = "POST_LOAD_FAIL";

export const POST_LOAD_USER_DETAILS_START = "POST_LOAD_USER_DETAILS_START";
export const POST_LOAD_USER_DETAILS_SUCCESS = "POST_LOAD_USER_DETAILS_SUCCESS";
export const POST_LOAD_USER_DETAILS_FAILED = "POST_LOAD_USER_DETAILS_FAILED";
